# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** [Mikalai Leanavets]

In [1]:
import numpy as np

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a

In [4]:
ceny_inflacja= ceny* 1.05
print(f'Ceny po inflacji 5% {ceny_inflacja.round(2)}')

Ceny po inflacji 5% [[ 31.49  33.59  30.44]
 [ 52.49  55.64  50.39]
 [ 15.74  16.79  14.69]
 [104.99 110.24  99.74]]


Zadanie 1b

In [6]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_promocyjne = ceny * (1 - rabaty)
print(f'Ceny po rabacie {ceny_promocyjne.round(2)}')

Ceny po rabacie [[26.99 30.39 24.64]
 [44.99 50.34 40.79]
 [13.49 15.19 11.89]
 [89.99 99.74 80.74]]


Zadanie 1c

In [7]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1+marza)
print(f'Koszt zakupów bez marzy:{koszt_zakupu.round(2)}')

Koszt zakupów bez marzy:[[23.07 24.61 22.3 ]
 [35.71 37.85 34.28]
 [11.99 12.79 11.19]
 [66.66 69.99 63.33]]


Zadanie 1d

In [8]:
indeksy_najtańszych = ceny.argmin(axis=1)
print('Najtańszy sklep dla każdego produktu:')
for i in range(len(produkty)):
    nazwa_produktu= produkty[i]
    nazwa_sklepu= sklepy[indeksy_najtańszych[i]]
    print(f'Produkt {nazwa_produktu}: {nazwa_sklepu}')

Najtańszy sklep dla każdego produktu:
Produkt A: Online
Produkt B: Online
Produkt C: Online
Produkt D: Online


Ćwiczenie 2

Zadanie 2a

In [9]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])


kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b

In [10]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])


wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c

In [12]:
sprzedaż_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
macierz_sprzedaż = sprzedaż_flat.reshape(6,2)
średnia= macierz_sprzedaż.mean(axis=1)
print(f'Średnia produktu {średnia}')
zmiana= macierz_sprzedaż[:,1] - macierz_sprzedaż[:,0]
print(f'Zmiana: {zmiana}')

Średnia produktu [150. 225. 215. 170. 240. 225.]
Zmiana: [100 150 -70 100 140 -70]


Zadanie 2d

In [13]:
wektor = kwartaly.flatten()
wektor_z_13 = np.concatenate([wektor, np.array([235])])
print(f'Tablica zawierająca 13 miesiące \n{wektor_z_13}')
print(f'Ilość elementów:{wektor_z_13.size}')

Tablica zawierająca 13 miesiące 
[120 135  98 142 167 189 201 178 156 143 198 221 235]
Ilość elementów:13


Ćwiczenie 3

In [14]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a

In [20]:
średnia = pensje.mean()
mediana= np.median(pensje)
odchylenie = pensje.std()

print(f'Średnia pensja : {średnia} zł')
print(f'Mediana pensja:{mediana} zł')
print(f'Odchylenie standartowe: {odchylenie} zł')
print(f'Pracownicy z pensją wyżej średniej {np.array(pracownicy) [pensje > średnia]}')
print(f' Pracownicy z pensją niżej mediany : {np.array(pracownicy)[pensje<mediana]}')
różnica = pensje.max() - pensje.min()
iqr= np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f'Różnica :{różnica} zł')
print(f'IQR: {iqr} zł')

Średnia pensja : 6425.0 zł
Mediana pensja:6050.0 zł
Odchylenie standartowe: 1616.9029037020127 zł
Pracownicy z pensją wyżej średniej ['Jan' 'Marek' 'Zofia']
 Pracownicy z pensją niżej mediany : ['Anna' 'Ewa' 'Piotr' 'Tomek']
Różnica :4900 zł
IQR: 2200.0 zł


Zadanie 3b

In [23]:
premie= np.where(oceny>= 4.5, 2000, np.where(oceny >=4.0, 1000,0))
nowe_wynagrodzenia= pensje+ premie
najwyzsza_premia_idx=premie.argmax()
print(f'Naliczone premie: {premie}')
print('Całe wynagrodzenie: {nowe_wynagrodzenie}')
print(f'Nawiększą premię otzymała {pracownicy[najwyzsza_premia_idx]}')

Naliczone premie: [1000    0 2000 1000 2000    0 1000    0]
Całe wynagrodzenie: {nowe_wynagrodzenie}
Nawiększą premię otzymała Ewa


Zadanie 3c

In [25]:
kolejność = np.argsort(pensje)[::-1]
print('Kolejność pracowników zgodnie z  premią:')
for i, idx in enumerate(kolejność, 1):
    print(f'{i}.{pracownicy[idx]} Pensja: {pensje[idx]} zł, Staż :{staz[idx]} lat')

Kolejność pracowników zgodnie z  premią:
1.Marek Pensja: 9100 zł, Staż :15 lat
2.Zofia Pensja: 8500 zł, Staż :12 lat
3.Jan Pensja: 7200 zł, Staż :8 lat
4.Kasia Pensja: 6300 zł, Staż :5 lat
5.Tomek Pensja: 5800 zł, Staż :4 lat
6.Anna Pensja: 5500 zł, Staż :3 lat
7.Ewa Pensja: 4800 zł, Staż :2 lat
8.Piotr Pensja: 4200 zł, Staż :1 lat


Zadanie 3d

In [27]:
kor_staz_pensja = np.corrcoef(staz, pensje)[0,1]
kor_staz_ocena= np.corrcoef(staz, oceny)[0,1]
print(f'Korelacje staz/ pensja {kor_staz_pensja}')
print(f'Korelacje staz/ocena {kor_staz_ocena}')
if abs(kor_staz_pensja)> abs(kor_staz_ocena):
    print('Korelacka między stażem i pensję jest mocniejsza')
else:
    print('Korelacja między stażem i oceną jest mocniejsza')    


Korelacje staz/ pensja 0.987862864584301
Korelacje staz/ocena 0.04198471605953067
Korelacka między stażem i pensję jest mocniejsza


Zadanie 3e

In [29]:
ceny_kol = ceny_produktow.reshape(4,1)
przychod = sprzedaz * ceny_kol
najlepszy_produkt_idx = przychod.sum(axis=1).argmax()
najlepszy_miesiac_idx = przychod.sum(axis=0).argmax()
pierwsze_3 = przychod[:,:3].sum()
ostatnie_3 = przychod[:,3:].sum()
print(f'Najwiekszy przychod od produktu: {produkty_nazwy[najlepszy_produkt_idx]}')
print(f'Najlepszy miesiąc łącznie {najlepszy_miesiac_idx + 1}')
print(f'Zarobki za piersze trzy miesiące:{pierwsze_3} zł')
print(f'Zarobki za ostatnie 3 niesiące:{ostatnie_3} zł')
if ostatnie_3>pierwsze_3:
    print('Trend rosnący')
else:
    print('Trend malejący')

Najwiekszy przychod od produktu: Smartfon
Najlepszy miesiąc łącznie 2
Zarobki za piersze trzy miesiące:2463950 zł
Zarobki za ostatnie 3 niesiące:2536500 zł
Trend rosnący


Ćwiczenie 4

In [39]:
np.random.seed(42)
wiek=np.clip(np.random.normal(35,10,100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500,200,100), 0, None)
wizyty =np.random.poisson(5,100)
print('Statystyki opisowe')
print(f'Wiek -> średnia:{wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std:{wiek.std():.1f}, min: {wiek.min()}, max:{wiek.max()}')
print(f'Wydatki -> średnia:{wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std:{wydatki.std():.1f}, min: {wydatki.min()}, max:{wydatki.max()}')
print(f'Wizyty -> średnia:{wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std:{wizyty.std():.1f}, min: {wizyty.min()}, max:{wizyty.max()}')
print('Korelacje')
kor_wiek_wydatki= np.corrcoef(wiek,wydatki)[0,1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0,1]
print(f'Korelacja wiek i wydatki:{kor_wiek_wydatki:.3f}')
print(f'Korelacjawizyty i wydatki:{kor_wizyty_wydatki:.3f}')
sr = wydatki.mean()
sd= wydatki.std()
warunki= [wydatki > (sr+sd), wydatki<(sr-sd)]
wybory= ['Wysoki', 'Niski']
segmenty = np.select(warunki, wybory, default = 'Średni')
print('Wyniki')
unikalne_segmenty, liczby_klientów= np.unique(segmenty, return_counts=True)
for segment, liczba in zip(unikalne_segmenty, liczby_klientów):
    procent=(liczba/len(segmenty)) *100
    print(f'Segment {segment}:{liczba} klientów ({procent:.0f})%')

Statystyki opisowe
Wiek -> średnia:33.6, mediana: 33.0, std:8.6, min: 18, max:53
Wydatki -> średnia:504.5, mediana: 516.8, std:189.8, min: 116.2457569401917, max:1044.0338333179238
Wizyty -> średnia:4.9, mediana: 5.0, std:2.2, min: 1, max:11
Korelacje
Korelacja wiek i wydatki:-0.120
Korelacjawizyty i wydatki:-0.159
Wyniki
Segment Niski:17 klientów (17)%
Segment Wysoki:12 klientów (12)%
Segment Średni:71 klientów (71)%
