# Zjazd 3, część 1 — NumPy
**Autor:** [Mikalai Leanavets]

In [2]:
import numpy as np

In [3]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [4]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [7]:
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int64


Ćwiczenie 2

In [11]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru
print(f'Sprzedaż w styczniu :{miesiace_sprzedaz[0]}')
print(f'Sprzedaż w grudniu :{miesiace_sprzedaz[-1]}')
print(f'Sprzedaż w Q1: {miesiace_sprzedaz[0:3]} ')
print(f'Sprzedaż w Q4: {miesiace_sprzedaz[-3:]} ')
print(f'Sprzedaż co drugi miesiąc: {miesiace_sprzedaz[::2]} ')
print(f'Sprzedaż od grudnia: {miesiace_sprzedaz[::-1]} ')

Sprzedaż w styczniu :120
Sprzedaż w grudniu :221
Sprzedaż w Q1: [120 135  98] 
Sprzedaż w Q4: [143 198 221] 
Sprzedaż co drugi miesiąc: [120  98 167 201 156 198] 
Sprzedaż od grudnia: [221 198 143 156 178 201 189 167 142  98 135 120] 


In [13]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
print(f'Sprzedaż produktu A w Q2 {dane[0,1]}')
print(f'Sprzedaż produktu C {dane[2,:]}')
print(f'Sprzedaż wszystkich produktów w Q1 {dane[:,0]}')
print(f'Sprzedaż produktów B i C w Q2 i Q3 {dane[1:3, 1:3]}')


Sprzedaż produktu A w Q2 145
Sprzedaż produktu C [234 267 289]
Sprzedaż wszystkich produktów w Q1 [120  89 234  56]
Sprzedaż produktów B i C w Q2 i Q3 [[102  95]
 [267 289]]


Ćwiczenie 3

In [14]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

zadanie 1

In [27]:
srednia_cena = ceny.mean()
indeks_max =ceny.argmax()
indeks_min=  ceny.argmin()
print(f'Średnia cena:{srednia_cena:.2f} zł')
print(f'Najdroższy product:{indeks_max} ({ceny[indeks_max]}) zł')
print(f'Najtańszy product:{indeks_min} ({ceny[indeks_min]}) zł')

Średnia cena:1171.00 zł
Najdroższy product:0 (3499) zł
Najtańszy product:4 (89) zł


zadanie 2

In [ ]:
wartość_produktów = ceny* ilosci_magazyn
wartość_magazynu= wartość_produktów.sum()
print (f'Wartość każdego produkta: {wartość_produktów} zł')
print(f'Wartość magazynu:{wartość_magazynu} zł')

Wartość każdego produkta: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Wartość magazynu:549465


Zadanie 3

In [31]:
rabat= ceny * 0.85
VAT= ceny * 1.23
Drożej_1000 = (ceny>1000).sum()
print(f'Cena z promocją:{rabat} zł')
print(f'Ceny z VAT: {VAT} zł')
print(f'Ilość produktów powyżej 1000 zł: {Drożej_1000}')

Cena z promocją:[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15] zł
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77] zł
Ilość produktów powyżej 1000 zł: 4


Zadanie 4

In [41]:
maska_oceny=oceny_klientow >=4.5
print(f'Produkty z oceną >=4.5: Nazwy:{np.array(nazwy)[maska_oceny]}\n Ceny: {ceny[maska_oceny]}')
maska_ceny= ceny < 200
print(f'Produkty poniżej 200 zł: Nazwy:{np.array(nazwy)[maska_ceny]}\n Ilości: {ilosci_magazyn[maska_ceny]}')

Produkty z oceną >=4.5: Nazwy:['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
 Ceny: [3499 2499  349 1499]
Produkty poniżej 200 zł: Nazwy:['Ładowarka' 'Mysz']
 Ilości: [312 201]


Zadanie 5

In [ ]:
maska_zapas = ilosci_magazyn < 30
wartosc_malo = wartość_produktów[maska_zapas].sum()
procent_magazynu= (wartosc_malo/wartość_magazynu) * 100
print(f'Produkty < 30 na stanie :{np.array(nazwy)[maska_zapas]}')
print(f'Łączna wartosc tyvh produktow:{wartosc_malo}')
print(f'Stanowią one {procent_magazynu:.2f}% magazynu')


Produkty < 30 na stanie :['Laptop' 'Monitor']
 Łączna wartosc tyvh produktow:86962
Stanowią one 15.83% magazynu


Zadanie 6

In [53]:
maska_okazja = (oceny_klientow >=4.5)& (ceny < 1000)
print(f'Specjalne okazje : {np.array(nazwy)[maska_okazja]}\n Ceny:{ceny[maska_okazja]}')
średnia1=ceny[oceny_klientow>=4.0].mean()
średnia2=ceny[oceny_klientow<4.0].mean()
print(f'Średnia cena produktów w oceną powyżej 4.0: {średnia1:.2f} zł')
print(f'Średnia cena produktów w oceną poniżej 4.0: {średnia2} zł')


Specjalne okazje : ['Słuchawki']
 Ceny:[349]
Średnia cena produktów w oceną powyżej 4.0: 1446.14 zł
Średnia cena produktów w oceną poniżej 4.0: 529.0 zł


Ćwiczenie 4


In [54]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  26.2 ms
NumPy:  1.3 ms
NumPy jest 21× szybszy!


In [55]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  9.7 ms
NumPy:  1.3 ms
NumPy jest 8× szybszy!


In [56]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  35.8 ms
NumPy:  1.3 ms
NumPy jest 27× szybszy!


## Wnioski z benchmarku
- NumPy jest 21x szybszy w mnożeniu
- NumPy jest 8x szybszy w sumowaniu
- NumPy jest 27x szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list 